name: Prueba de Carga con k6

on: [push] # Ejecuta la prueba de carga en cada push

jobs:
  k6:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v2

      - name: Instalar k6
        run: |
          curl -sfL https://get.k6.io | sh
          sudo mv k6 /usr/local/bin/
        shell: bash

      - name: Ejecutar prueba de carga
        run: k6 run script.js
